### ISSUE TITLE
Typhoeus return message lost when creating a Webmock response

### ISSUE THREAD

**Issue by thebravoman** [bblimke/webmock#1057]
Send request to "http://post_zip.pixel/2"
This is invalid and typhoeus will return code:0 return_message: "Couldn't resolve host name" 

This is lost when creating the webmock response
```[78, 87] in /Users/kireto/.rvm/gems/.../gems/webmock-3.14.0/lib/webmock/http_lib_adapters/typhoeus_hydra_adapter.rb
   78:           request_signature
   79:         end
   80: 
   81: 
   82:         def self.build_webmock_response(typhoeus_response)
=> 83:           webmock_response = WebMock::Response.new
   84:           webmock_response.status = [typhoeus_response.code, typhoeus_response.status_message]
   85:           webmock_response.body = typhoeus_response.body
   86:           webmock_response.headers = typhoeus_response.headers
   87:           webmock_response
(byebug) typhoeus_response
#<Typhoeus::Response:0x0000000112c8a920 @options={:httpauth_avail=>0, :total_time=>0.000744, :starttransfer_time=>0.0, :appconnect_time=>0.0, :pretransfer_time=>0.0, :connect_time=>0.0, :namelookup_time=>0.0, :redirect_time=>0.0, :effective_url=>"http://post_zip.pixel/2", :primary_ip=>"", :response_code=>0, :request_size=>0, :redirect_count=>0, :size_upload=>0.0, :size_download=>0.0, :speed_upload=>0.0, :speed_download=>0.0, :return_code=>:couldnt_resolve_host, :response_headers=>"", :response_body=>"", :debug_info=>#<Ethon::Easy::DebugInfo:0x0000000112c714c0 @messages=[]>}, @request=#<Typhoeus::Request:0x00000001220ed698 @base_url="http://post_zip.pixel/2", @original_options={:method=>"post", :timeout=>5}, @options={:method=>"post", :timeout=>5, :headers=>{"User-Agent"=>"RetreaverPinger/2.0 (+https://retreaver.com/bot)", "Expect"=>""}, :maxredirs=>50}, @on_complete=[#<Proc:0x00000001220ed418 /Users/kireto/axles/code/callpixels/lib/pinger_diversion.rb:213>], @__webmock_request_signature=#<WebMock::RequestSignature:0x00000001220f7558 @method=:post, @uri=#<Addressable::URI:0x4e46c URI:http://post_zip.pixel:80/2>, @body=nil, @headers={"User-Agent"=>"RetreaverPinger/2.0 (+https://retreaver.com/bot)", "Expect"=>""}, @__typed_vcr_request=#<struct VCR::Request method=:post, uri="http://post_zip.pixel/2", body="", headers={"User-Agent"=>["RetreaverPinger/2.0 (+https://retreaver.com/bot)"], "Expect"=>[""]}>>, @block_connection=false, @response=#<Typhoeus::Response:0x0000000112c8a920 ...>, @on_failure=[]>, @first_header_line=nil, @status_message=nil, @headers={}>
(byebug) typhoeus_response.status_message
nil
(byebug) typhoeus_response.return_message
"Couldn't resolve host name"
(byebug) 
```

Status_message is nil and the return_message is "Could't resolve host name"
When the status is created it is done as 
webmock_response.status = [typhoeus_response.code, typhoeus_response.status_message]

From there on the actual problem for my case is that this gets saved in a vcr cassette as 

```
- request:
    method: post
    uri: http://post_zip.pixel/2
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - RetreaverPinger/2.0 (+https://retreaver.com/bot)
      Expect:
      - ''
  response:
    status:
      code: 0
      message:
    headers: {}
    body:
      encoding: ASCII-8BIT
      string: ''
  recorded_at: Fri, 03 May 2024 07:59:00 GMT
```
where the status code is 0 and the message is empty.

This leads to the following situation. The first time a request is made and there is no cassette typhoeus has return_message as "Could not resolve host" and  we can test in our specs that the host was not reached and we've shown the user the error message.

The second time the spec is ran there is already a cassette. The cassette has status message as empty and the test no longer works as it does not load "could not resolve host" into the typhoeus return_message
