### ISSUE TITLE
[httpclient] adapter doesn't mock properly requests issued via HTTPClient#get

### ISSUE THREAD

**Issue by miguelff** [bblimke/webmock#322]
In particular, it doesn't take into account header values provided to `HTTPClient` and delegated to  `HTTPClient::SessionManager`

The following example fails:

``` ruby
  it "provides user-agent on each request" do
    user_agent = "MyUserAgent/0.1"
    stub_request(:get, "www.example.com/user-agent").to_return do |request|
      {:body => request.headers["User-Agent"]}
    end
    client= HTTPClient.new(:agent_name => user_agent)
    res = client.get("www.example.com/user-agent")
    res.body.should == user_agent
  end
```

Message is:

```
Failures:

  1) Almodovar::ClientWrapper provides user-agent on each request
     Failure/Error: res.body.should == user_agent
       expected: "MyUserAgent/0.1"
            got: "" (using ==)
     # ./spec/unit/http_session_spec.rb:29:in `block (2 levels) in <top (required)>'
```
