### ISSUE TITLE
Webmock net_http_response modifies stub body when running on ruby-head

### ISSUE THREAD

**Issue by iarkhanhelsky** [bblimke/webmock#773]
Following example runs fine on `ruby-2.5.1`, but fails on `ruby-head`:

```ruby
require 'rspec'
require 'webmock/rspec'
require 'open-uri'

describe 'webmock stub response body' do
	let(:data) { 'ABC'.freeze }
	let(:url) { 'https://example.com/resource' }

	it do
		stub_request(:get, url).to_return(status: 200, body: data)
		expect(open(url).read).to eq(data)
	end
end
```
If `data` string not frozen it appears to be empty after `open(url)` call. 

# Fail log

```
F

Failures:

  1) webmock stub response body 
     Failure/Error: response_data = open(url).read

     FrozenError:
       can't modify frozen String
     # ./.rvm/gems/ruby-head/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http_response.rb:26:in `read_body'
     # ./.rvm/gems/ruby-head/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:177:in `build_net_http_response'
     # ./.rvm/gems/ruby-head/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:83:in `request'
     # ./.rvm/gems/ruby-head/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
     # ./.rvm/gems/ruby-head/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
     # ./test.rb:11:in `block (2 levels) in <top (required)>'
```
