### ISSUE TITLE
Escaping of `hash_including` goes wrong.

### ISSUE THREAD

**Issue by iDuuck** [bblimke/webmock#916]
Hey guys, I am currently into testing my application, which is communicating with the OneSignal API. Now I stumbled upon a problem, and I can't seem to find anything on the web related to RoR or even Ruby alone.

I am receiving the following error:
```bash
The request POST https://onesignal.com/api/v1/notifications with body hash_including({"contents"=>{"de"=>"BlaBlaBla & BlaBlaBla", "en"=>"BlaBlaBla & BlaBlaBla"}}) was expected to execute 1 time but it executed 0 times

The following requests were made:

POST https://onesignal.com/api/v1/notifications with body '{"app_id":"<APPID_REMOVED>","headings":{"en":"Your dog needs some attention.","de":"Dein Hund braucht Aufmerksamkeit."},"contents":{"en":"BlaBlaBla \u0026 BlaBlaBla","de":"BlaBlaBla \u0026 BlaBlaBla"},"include_player_ids":["test-user-id"]}' with headers <HEADERS_REMOVED> was made 1 time
```

See the `\u0026`? Why is it escaping like that? I also tried hard-coding the `\0026` manually in the tests, but it also didn't work.

The code I am using for the test:

```ruby
let(:asserted_configuration) do
  {
    de: I18n.t('workers.send_recurring_notifications.content', locale: :de, titles: 'FooBar & BarFoo'),
    en: I18n.t('workers.send_recurring_notifications.content', locale: :en, titles: 'FooBar & BarFoo')
  }
end

it 'posts the right content to onesignal' do
  mock = stub_request(:post, 'https://onesignal.com/api/v1/notifications')
           .with(body: hash_including({ contents: asserted_configuration }))

  subject.perform(arguments)

  expect(mock).to have_been_requested.times(1)
end
```

**Comment by iDuuck** [comment]
Important to note, that this is happening only on CircleCI! On my mac this is not a problem.

**Comment by bblimke** [comment]
What are the differences between CircleCI env and your local env? Same Ruby?

**Comment by iDuuck** [comment]
Sorry for inactivity, was in another project. Yeah, we got the same ruby. Don't know, if there is anything regarding the encoding that ruby offers?

**Comment by bblimke** [comment]
What version of Ruby is that?

**Comment by iDuuck** [comment]
It's ruby version: `2.6.3p62`

CircleCI configuration is like this (this isn't related to the "ruby" orb, it also happens without it):

```yml
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

executors:
  docker-executor:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          COVERAGE: true
          PGHOST: 127.0.0.1
          PGUSER: user
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: db
          POSTGRES_PASSWORD: ""

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.1.4
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - ruby/rspec-test

```
